### ISSUE TITLE
Breakfast recipe request

### ISSUE THREAD

**Issue by CorrineMarquardt** [IntroToCode/Spring21_Recipes_Codemates10#1]
## 💬 Discussion topic

I would like the best recipe for a breakfast I am making for myself and 5 friends (6 people total). One of the friends is a vegetarian and I have an hour set aside the morning of the breakfast for prep and cooking. I would like the meal to be nutritious, budget-friendly, and of course, delicious!

## ❗ Potential issues

Ingredients (include quantities)
Prep Work
Cooking Instructions

## 👥 People to consult

Corrine Marquardt, Gordon Ramsay

## 📃 Details

Acceptance criteria:
At least one fruit included
At least one vegetable included
At least one protein included
Vegetarian-friendly
Budget of $30 total
Prep + Cook Time Under 60 minutes
Must feed at least 6 adults
Tasty!

Please include any cooking equipment and utensils needed to prepare the meal in your recipe

**Comment by CorrineMarquardt** [comment]
@Amayesing @dpanic286 @mrayxu - any ideas on great breakfast meal recipes that meet the criteria above?

**Comment by mrayxu** [comment]
How about a delicious and simple tofu egg scramble?

**Comment by CorrineMarquardt** [comment]
@mrayxu - that sounds delicious! Please post the recipe as a pull request to get us started.

Top of mind challenges with this idea are inclusion of the veggie and fruit, but looking forward to what you provide!

**Comment by mrayxu** [comment]
Do avocados count as fruit....?

**Comment by Amayesing** [comment]
Can we add a little fruit medley on the side? Avocados technically count I think.

**Comment by Amayesing** [comment]
Did not know merging his edit would close the issue

**Comment by dpanic286** [comment]
6 eggs for 6 people - do we need more eggs? Maybe 12?

**Comment by mrayxu** [comment]
that makes sense. do you want to commit it to my pull request @dpanic286 ?

**Comment by dpanic286** [comment]
> that makes sense. do you want to commit it to my pull request @dpanic286 ?

For some reason just now saw your comment from above. I see this is updated to include the 12 eggs so looks good! Just added the missing oil in the ingredients list. 

Should be good to close from my end after that

**Comment by CorrineMarquardt** [comment]
Recipe looks great - closing this issue now. Thanks, all!
