### ISSUE TITLE
Lunch Food

### ISSUE THREAD

**Issue by dpanic286** [IntroToCode/Spring21_Recipes_Codemates10#2]
## 💬 Discussion topic

I would like the best recipe for a lunch for 4 people. One of my friends has a shellfish allergy and another friend has a peanut allergy. I have all day for prep and cooking since I want to impress. I would like the meal to be nutritious but most importantly delicious!

## ❗ Potential issues
Ingredients (include quantities)
Prep Work
Cooking Instructions

## 👥 People to consult
@dpanic286, @mrayxu, @CorrineMarquardt, @amayesing

## 📃 Details
Acceptance criteria:
Shell-fish free
Peanut-free
Budget of $75 total
Prep + Cook Time Under 3 hours
Must feed at least 4 adults
Delicious!

Please include any cooking equipment and utensils needed to prepare the meal in your recipe

**Comment by dpanic286** [comment]
Any ideas @CorrineMarquardt @Amayesing @mrayxu?

The world is our oyster!!!

**Comment by CorrineMarquardt** [comment]
On it now, @dpanic286 ! Adding a great chicken recipe - will open the pull request shortly!
